### ISSUE TITLE
project dropdown positioning seems off

### ISSUE THREAD

**Issue by roberrrt-s** [roberrrt-s/designs#1]
Taking this code as reference:

(sass/custom/shared/dashboard/side-menu.scss)

``` css
li {
    &.select-dropdown {
        border: solid 1px $color-menu-items;
        border-radius: 5px;
        padding: ($margin-input-small);
        font-size: $font-size-menu-subpage;
        z-index: 1;
        display: block;
        position: relative;
        width: 170px;

        .icon {
            top: 0;
        }
        .submenu {

            visibility: hidden;
            opacity: 0;
            display: none;
            padding: 0 $margin-input-small;
            z-index: -1;
            background: $color-background-quaternary;
            color: $color-shading-purple;
            font-size: $font-size-button;
            position: absolute;
            left: 0px;
            border-radius: 5px;
            border: solid 1px $color-menu-items;
            border-top: 0;
            width: 170px;

            a {
                text-overflow: ellipsis;
                white-space: nowrap;
                overflow: hidden;
            }
        }
    }
    &.select-dropdown:hover {

        .icon {
            transform: scaleY(-1);
            filter: FlipH;
        }

        .submenu {
            border-top-left-radius: 0;
            border-top-right-radius: 0;
            visibility: visible;
            opacity: 1;
            display: inline-block;
            padding: $margin-input-small;
        }

    }

}
```

Positions the dropdown directly under the `select-dropdown` but doesn't fill up the entire 100%. it has something to do with either the % based units, or the fact i'm removing it from the document flow.
